### PR TITLE
add `indextree` and `generational-indextree`

### PR DESCRIPTION
**Pull request by smallstepman**
- https://crates.io/crates/indextree 
- https://crates.io/crates/generational-indextree

### CODE REVIEW

**Comment by mooman219** [comment]
I have a new PC (7950X3D) that I've been setting up, so I'll have to rerun all of the tests again to get a reasonable comparison. I'll look into it, I'll likely have to restrict this to a small number of cores to prevent invalid results.

**Comment by smallstepman** [comment]
btw, now you mentioned multiple cores,I realized I haven't enabled `par_iter` or `rayon` features for `indextree`... Would you be open to reviewing another PR that benchmarks `indextree` but running in multithreaded mode?

**Comment by smallstepman** [comment]
also one question, what command are you running to get those nice graphs? `cargo bench` doesn't do it for me

**Comment by mooman219** [comment]
> nice, if you're interested I can also run these benchmarks on m1 pro, m2, or 64 core gen 3 epyc

That'll probably make this a better benchmark, but not really that important since these are all synthetic benchmarks in the first place. I could probably make a folder for results from other systems and people that want to deep dive can interpret it as they will.

> also one question, what command are you running to get those nice graphs? cargo bench doesn't do it for me

Google Spreadsheet, I wrote a regex that just formats the criterion output into a CSV that I load into google sheets and a graph is just watching the range for updates. I could probably setup gnuplot to look how I want.. but that was a bit more effort. Here's some preliminary results:

image

> btw, now you mentioned multiple cores,I realized I haven't enabled par_iter or rayon features for indextree... Would you be open to reviewing another PR that benchmarks indextree but running in multithreaded mode?

Probably interesting, but I do not want to explore that right now given like most of these don't support that, and it's more fraught with variation I have to account for.

**Comment by smallstepman** [comment]
thanks for the quick action!

**Comment by ofek** [comment]
Can you update the readme with that new benchmark picture?

**Comment by corneliusroemer** [comment]
I made an issue to request addition of the 2 crates to the benchmark pictures: #5

**Pull request merged**
